import { FacilityData, EmployeeData } from './table-data.interface';

export const MOCK_FACILITY_DATA: FacilityData[] = [
  {
    id: 'TSK-001',
    facilityName: 'סניף דואר תל אביב מרכז',
    address: 'דיזנגוף 50, תל אביב',
    contactName: 'יעקב כהן',
    contactPhone: '050-1234567',
    bagCount: 3,
    totalAmount: 125000,
    status: 'ready',
    hub: 'center',
    hubName: 'מוקד מרכז',
    deliveryType: 'delivery',
    targetFacility: 'סניף דואר תל אביב מרכז',
    createdAt: '2024-01-15',
    barcodes: [
      { barcode: 'RR123456789IL', type: 'רגיש', amount: 50000 },
      { barcode: 'RR123456790IL', type: 'רגיל', amount: 45000 },
      { barcode: 'RR123456791IL', type: 'מוגן', amount: 30000 },
    ],
    team: {
      teamLeader: 'דוד לוי',
      driver: 'אבי ישראלי',
      security1: 'יוסי כץ',
      security2: 'אורן שלום',
    },
  },
  {
    id: 'TSK-002',
    facilityName: 'סניף דואר ירושלים',
    address: 'יפו 23, ירושלים',
    contactName: 'שרה לוי',
    contactPhone: '052-9876543',
    bagCount: 2,
    totalAmount: 87000,
    status: 'inProgress',
    hub: 'center',
    hubName: 'מוקד מרכז',
    deliveryType: 'pickup',
    targetFacility: 'סניף דואר ירושלים',
    createdAt: '2024-01-16',
    barcodes: [
      { barcode: 'RR223456789IL', type: 'רגיל', amount: 47000 },
      { barcode: 'RR223456790IL', type: 'רגיל', amount: 40000 },
    ],
    team: {
      teamLeader: 'משה כהן',
      driver: 'דני ישראלי',
      security1: 'רון כץ',
      security2: 'עמית שלום',
    },
  },
  {
    id: 'TSK-003',
    facilityName: 'סניף דואר חיפה',
    address: 'הנמל 15, חיפה',
    contactName: 'מיכאל ברק',
    contactPhone: '054-5551234',
    bagCount: 4,
    totalAmount: 210000,
    status: 'urgent',
    hub: 'north',
    hubName: 'מוקד צפון',
    deliveryType: 'delivery',
    targetFacility: 'סניף דואר חיפה',
    createdAt: '2024-01-14',
    barcodes: [
      { barcode: 'RR323456789IL', type: 'רגיש', amount: 120000 },
      { barcode: 'RR323456790IL', type: 'מוגן', amount: 90000 },
    ],
    team: {
      teamLeader: 'יוסי אברהם',
      driver: 'רוני כהן',
      security1: 'דני לוי',
      security2: 'אלי ישראלי',
    },
  },
  {
    id: 'TSK-004',
    facilityName: 'סניף דואר באר שבע',
    address: 'רגר 8, באר שבע',
    contactPhone: '053-7778899',
    contactName: 'רחל אברהם',
    bagCount: 1,
    totalAmount: 32000,
    status: 'completed',
    hub: 'south',
    hubName: 'מוקד דרום',
    deliveryType: 'delivery',
    targetFacility: 'סניף דואר באר שבע',
    createdAt: '2024-01-13',
    barcodes: [{ barcode: 'RR423456789IL', type: 'רגיל', amount: 32000 }],
    team: {
      teamLeader: 'אבי שבע',
      driver: 'משה דרום',
      security1: 'יוסי אבן',
      security2: 'דוד נגב',
    },
  },
  {
    id: 'TSK-005',
    facilityName: 'סניף דואר אילת',
    address: 'התמרים 12, אילת',
    contactName: 'דני גולן',
    contactPhone: '050-1112233',
    bagCount: 2,
    totalAmount: 45000,
    status: 'ready',
    hub: 'south',
    hubName: 'מוקד דרום',
    deliveryType: 'delivery',
    targetFacility: 'סניף דואר אילת',
    createdAt: '2024-01-16',
    barcodes: [
      { barcode: 'RR523456789IL', type: 'רגיל', amount: 25000 },
      { barcode: 'RR523456790IL', type: 'רגיש', amount: 20000 },
    ],
    team: {
      teamLeader: 'רוני ים',
      driver: 'משה סוף',
      security1: 'דני חוף',
      security2: 'יוסי שמש',
    },
  },
  {
    id: 'TSK-006',
    facilityName: 'סניף דואר נתניה',
    address: 'הרצל 45, נתניה',
    contactName: 'אורית שמש',
    contactPhone: '052-4445566',
    bagCount: 3,
    totalAmount: 156000,
    status: 'urgent',
    hub: 'center',
    hubName: 'מוקד מרכז',
    deliveryType: 'pickup',
    targetFacility: 'סניף דואר נתניה',
    createdAt: '2024-01-15',
    barcodes: [
      { barcode: 'RR623456789IL', type: 'רגיש', amount: 86000 },
      { barcode: 'RR623456790IL', type: 'מוגן', amount: 70000 },
    ],
    team: {
      teamLeader: 'משה חוף',
      driver: 'דני ים',
      security1: 'רוני גל',
      security2: 'יוסי שרון',
    },
  },
  {
    id: 'TSK-007',
    facilityName: 'סניף דואר עכו',
    address: 'כ"ן עתיק 30, עכו',
    contactName: 'נעמי ירון',
    contactPhone: '054-9998877',
    bagCount: 2,
    totalAmount: 68000,
    status: 'inProgress',
    hub: 'north',
    hubName: 'מוקד צפון',
    deliveryType: 'delivery',
    targetFacility: 'סניף דואר עכו',
    createdAt: '2024-01-16',
    barcodes: [
      { barcode: 'RR723456789IL', type: 'רגיל', amount: 38000 },
      { barcode: 'RR723456790IL', type: 'רגיל', amount: 30000 },
    ],
    team: {
      teamLeader: 'דוד צפון',
      driver: 'משה עתיק',
      security1: 'יוסי חומה',
      security2: 'רוני שער',
    },
  },
  {
    id: 'TSK-008',
    facilityName: 'סניף דואר אשדוד',
    address: 'הבנים 5, אשדוד',
    contactName: 'יוסף הלכה',
    contactPhone: '050-6667788',
    bagCount: 1,
    totalAmount: 22000,
    status: 'completed',
    hub: 'south',
    hubName: 'מוקד דרום',
    deliveryType: 'pickup',
    targetFacility: 'סניף דואר אשדוד',
    createdAt: '2024-01-12',
    barcodes: [{ barcode: 'RR823456789IL', type: 'רגיל', amount: 22000 }],
    team: {
      teamLeader: 'אבי נמל',
      driver: 'דני ספן',
      security1: 'משה עוגן',
      security2: 'רוני גלים',
    },
  },
];

// Employee data - demonstrates table works with completely different data structures
export const MOCK_EMPLOYEE_DATA: EmployeeData[] = [
  {
    id: 'EMP-001',
    fullName: 'Sarah Cohen',
    email: 'sarah.cohen@company.com',
    phone: '050-1234567',
    department: 'Engineering',
    position: 'Senior Software Engineer',
    salary: 25000,
    startDate: '2020-03-15',
    status: 'active',
    skills: ['TypeScript', 'Angular', 'Node.js', 'AWS'],
    location: {
      office: 'Building A',
      city: 'Tel Aviv',
    },
    performance: {
      rating: 4.8,
      lastReview: '2024-01-10',
    },
  },
  {
    id: 'EMP-002',
    fullName: 'David Levi',
    email: 'david.levi@company.com',
    phone: '052-9876543',
    department: 'Product',
    position: 'Product Manager',
    salary: 28000,
    startDate: '2019-07-01',
    status: 'active',
    skills: ['Product Strategy', 'Agile', 'Data Analysis', 'UX'],
    location: {
      office: 'Building B',
      city: 'Tel Aviv',
    },
    performance: {
      rating: 4.9,
      lastReview: '2024-01-08',
    },
  },
  {
    id: 'EMP-003',
    fullName: 'Maya Goldstein',
    email: 'maya.goldstein@company.com',
    phone: '054-5551234',
    department: 'Design',
    position: 'UX Designer',
    salary: 22000,
    startDate: '2021-01-10',
    status: 'remote',
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems'],
    location: {
      office: 'Remote',
      city: 'Haifa',
    },
    performance: {
      rating: 4.7,
      lastReview: '2023-12-20',
    },
  },
  {
    id: 'EMP-004',
    fullName: 'Michael Bar',
    email: 'michael.bar@company.com',
    phone: '053-7778899',
    department: 'Engineering',
    position: 'DevOps Engineer',
    salary: 27000,
    startDate: '2018-11-20',
    status: 'active',
    skills: ['Kubernetes', 'Docker', 'CI/CD', 'Terraform'],
    location: {
      office: 'Building A',
      city: 'Tel Aviv',
    },
    performance: {
      rating: 4.6,
      lastReview: '2024-01-05',
    },
  },
  {
    id: 'EMP-005',
    fullName: 'Rachel Abramov',
    email: 'rachel.abramov@company.com',
    phone: '050-1112233',
    department: 'Marketing',
    position: 'Marketing Manager',
    salary: 24000,
    startDate: '2020-09-01',
    status: 'onLeave',
    skills: ['Digital Marketing', 'SEO', 'Content Strategy', 'Analytics'],
    location: {
      office: 'Building C',
      city: 'Jerusalem',
    },
    performance: {
      rating: 4.5,
      lastReview: '2023-12-15',
    },
  },
  {
    id: 'EMP-006',
    fullName: 'Yossi Klein',
    email: 'yossi.klein@company.com',
    phone: '052-4445566',
    department: 'Engineering',
    position: 'Frontend Developer',
    salary: 20000,
    startDate: '2022-02-14',
    status: 'active',
    skills: ['React', 'CSS', 'JavaScript', 'Responsive Design'],
    location: {
      office: 'Building A',
      city: 'Tel Aviv',
    },
    performance: {
      rating: 4.3,
      lastReview: '2024-01-12',
    },
  },
  {
    id: 'EMP-007',
    fullName: 'Naomi Stein',
    email: 'naomi.stein@company.com',
    phone: '054-9998877',
    department: 'HR',
    position: 'HR Manager',
    salary: 23000,
    startDate: '2019-05-20',
    status: 'active',
    skills: ['Recruitment', 'Employee Relations', 'Training', 'Compensation'],
    location: {
      office: 'Building B',
      city: 'Tel Aviv',
    },
    performance: {
      rating: 4.8,
      lastReview: '2024-01-03',
    },
  },
  {
    id: 'EMP-008',
    fullName: 'Dan Shapiro',
    email: 'dan.shapiro@company.com',
    phone: '050-6667788',
    department: 'Sales',
    position: 'Sales Representative',
    salary: 18000,
    startDate: '2023-06-01',
    status: 'active',
    skills: ['B2B Sales', 'CRM', 'Negotiation', 'Customer Relations'],
    location: {
      office: 'Building C',
      city: 'Jerusalem',
    },
    performance: {
      rating: 4.2,
      lastReview: '2023-12-28',
    },
  },
  {
    id: 'EMP-009',
    fullName: 'Tamar Israeli',
    email: 'tamar.israeli@company.com',
    phone: '052-3334455',
    department: 'Engineering',
    position: 'Backend Developer',
    salary: 24000,
    startDate: '2021-08-15',
    status: 'remote',
    skills: ['Python', 'Django', 'PostgreSQL', 'Redis'],
    location: {
      office: 'Remote',
      city: 'Beer Sheva',
    },
    performance: {
      rating: 4.7,
      lastReview: '2024-01-11',
    },
  },
  {
    id: 'EMP-010',
    fullName: 'Avi Rosenberg',
    email: 'avi.rosenberg@company.com',
    phone: '054-2221133',
    department: 'Finance',
    position: 'Financial Analyst',
    salary: 21000,
    startDate: '2020-12-01',
    status: 'inactive',
    skills: ['Financial Modeling', 'Excel', 'Reporting', 'Budgeting'],
    location: {
      office: 'Building B',
      city: 'Tel Aviv',
    },
    performance: {
      rating: 4.4,
      lastReview: '2023-11-30',
    },
  },
];

// Example: Product mock data for testing table flexibility
export const MOCK_PRODUCT_DATA = [
  {
    id: 'PRD-001',
    name: 'Laptop',
    category: 'Electronics',
    price: 4200,
    inStock: true,
    rating: 4.7,
    tags: ['computer', 'portable', 'office'],
    added: '2025-12-01',
  },
  {
    id: 'PRD-002',
    name: 'Desk Chair',
    category: 'Furniture',
    price: 850,
    inStock: false,
    rating: 4.2,
    tags: ['office', 'ergonomic'],
    added: '2025-11-15',
  },
  {
    id: 'PRD-003',
    name: 'Coffee Maker',
    category: 'Appliances',
    price: 320,
    inStock: true,
    rating: 4.9,
    tags: ['kitchen', 'coffee'],
    added: '2025-10-20',
  },
  {
    id: 'PRD-004',
    name: 'Bluetooth Speaker',
    category: 'Electronics',
    price: 390,
    inStock: true,
    rating: 4.5,
    tags: ['audio', 'portable'],
    added: '2025-09-05',
  },
];
