import { FacilityData } from './table-data.interface';

export const MOCK_FACILITY_DATA: FacilityData[] = [
  {
    id: 'TSK-001',
    facilityName: 'סניף דואר תל אביב מרכז',
    address: 'דיזנגוף 50, תל אביב',
    contactName: 'יעקב כהן',
    contactPhone: '050-1234567',
    bagCount: 3,
    totalAmount: 125000,
    status: 'ready',
    hub: 'center',
    hubName: 'מוקד מרכז',
    deliveryType: 'delivery',
    targetFacility: 'סניף דואר תל אביב מרכז',
    createdAt: '2024-01-15',
    barcodes: [
      { barcode: 'RR123456789IL', type: 'רגיש', amount: 50000 },
      { barcode: 'RR123456790IL', type: 'רגיל', amount: 45000 },
      { barcode: 'RR123456791IL', type: 'מוגן', amount: 30000 },
    ],
    team: {
      teamLeader: 'דוד לוי',
      driver: 'אבי ישראלי',
      security1: 'יוסי כץ',
      security2: 'אורן שלום',
    },
  },
  {
    id: 'TSK-002',
    facilityName: 'סניף דואר ירושלים',
    address: 'יפו 23, ירושלים',
    contactName: 'שרה לוי',
    contactPhone: '052-9876543',
    bagCount: 2,
    totalAmount: 87000,
    status: 'inProgress',
    hub: 'center',
    hubName: 'מוקד מרכז',
    deliveryType: 'pickup',
    targetFacility: 'סניף דואר ירושלים',
    createdAt: '2024-01-16',
    barcodes: [
      { barcode: 'RR223456789IL', type: 'רגיל', amount: 47000 },
      { barcode: 'RR223456790IL', type: 'רגיל', amount: 40000 },
    ],
    team: {
      teamLeader: 'משה כהן',
      driver: 'דני ישראלי',
      security1: 'רון כץ',
      security2: 'עמית שלום',
    },
  },
  {
    id: 'TSK-003',
    facilityName: 'סניף דואר חיפה',
    address: 'הנמל 15, חיפה',
    contactName: 'מיכאל ברק',
    contactPhone: '054-5551234',
    bagCount: 4,
    totalAmount: 210000,
    status: 'urgent',
    hub: 'north',
    hubName: 'מוקד צפון',
    deliveryType: 'delivery',
    targetFacility: 'סניף דואר חיפה',
    createdAt: '2024-01-14',
    barcodes: [
      { barcode: 'RR323456789IL', type: 'רגיש', amount: 120000 },
      { barcode: 'RR323456790IL', type: 'מוגן', amount: 90000 },
    ],
    team: {
      teamLeader: 'יוסי אברהם',
      driver: 'רוני כהן',
      security1: 'דני לוי',
      security2: 'אלי ישראלי',
    },
  },
  {
    id: 'TSK-004',
    facilityName: 'סניף דואר באר שבע',
    address: 'רגר 8, באר שבע',
    contactPhone: '053-7778899',
    contactName: 'רחל אברהם',
    bagCount: 1,
    totalAmount: 32000,
    status: 'completed',
    hub: 'south',
    hubName: 'מוקד דרום',
    deliveryType: 'delivery',
    targetFacility: 'סניף דואר באר שבע',
    createdAt: '2024-01-13',
    barcodes: [{ barcode: 'RR423456789IL', type: 'רגיל', amount: 32000 }],
    team: {
      teamLeader: 'אבי שבע',
      driver: 'משה דרום',
      security1: 'יוסי אבן',
      security2: 'דוד נגב',
    },
  },
  {
    id: 'TSK-005',
    facilityName: 'סניף דואר אילת',
    address: 'התמרים 12, אילת',
    contactName: 'דני גולן',
    contactPhone: '050-1112233',
    bagCount: 2,
    totalAmount: 45000,
    status: 'ready',
    hub: 'south',
    hubName: 'מוקד דרום',
    deliveryType: 'delivery',
    targetFacility: 'סניף דואר אילת',
    createdAt: '2024-01-16',
    barcodes: [
      { barcode: 'RR523456789IL', type: 'רגיל', amount: 25000 },
      { barcode: 'RR523456790IL', type: 'רגיש', amount: 20000 },
    ],
    team: {
      teamLeader: 'רוני ים',
      driver: 'משה סוף',
      security1: 'דני חוף',
      security2: 'יוסי שמש',
    },
  },
  {
    id: 'TSK-006',
    facilityName: 'סניף דואר נתניה',
    address: 'הרצל 45, נתניה',
    contactName: 'אורית שמש',
    contactPhone: '052-4445566',
    bagCount: 3,
    totalAmount: 156000,
    status: 'urgent',
    hub: 'center',
    hubName: 'מוקד מרכז',
    deliveryType: 'pickup',
    targetFacility: 'סניף דואר נתניה',
    createdAt: '2024-01-15',
    barcodes: [
      { barcode: 'RR623456789IL', type: 'רגיש', amount: 86000 },
      { barcode: 'RR623456790IL', type: 'מוגן', amount: 70000 },
    ],
    team: {
      teamLeader: 'משה חוף',
      driver: 'דני ים',
      security1: 'רוני גל',
      security2: 'יוסי שרון',
    },
  },
  {
    id: 'TSK-007',
    facilityName: 'סניף דואר עכו',
    address: 'כ"ן עתיק 30, עכו',
    contactName: 'נעמי ירון',
    contactPhone: '054-9998877',
    bagCount: 2,
    totalAmount: 68000,
    status: 'inProgress',
    hub: 'north',
    hubName: 'מוקד צפון',
    deliveryType: 'delivery',
    targetFacility: 'סניף דואר עכו',
    createdAt: '2024-01-16',
    barcodes: [
      { barcode: 'RR723456789IL', type: 'רגיל', amount: 38000 },
      { barcode: 'RR723456790IL', type: 'רגיל', amount: 30000 },
    ],
    team: {
      teamLeader: 'דוד צפון',
      driver: 'משה עתיק',
      security1: 'יוסי חומה',
      security2: 'רוני שער',
    },
  },
  {
    id: 'TSK-008',
    facilityName: 'סניף דואר אשדוד',
    address: 'הבנים 5, אשדוד',
    contactName: 'יוסף הלכה',
    contactPhone: '050-6667788',
    bagCount: 1,
    totalAmount: 22000,
    status: 'completed',
    hub: 'south',
    hubName: 'מוקד דרום',
    deliveryType: 'pickup',
    targetFacility: 'סניף דואר אשדוד',
    createdAt: '2024-01-12',
    barcodes: [{ barcode: 'RR823456789IL', type: 'רגיל', amount: 22000 }],
    team: {
      teamLeader: 'אבי נמל',
      driver: 'דני ספן',
      security1: 'משה עוגן',
      security2: 'רוני גלים',
    },
  },
];
