import { TableConfig } from '../models/table.config.interface';
import { EmployeeData } from '../models/table-data.interface';

export const employeeTableConfig: TableConfig<EmployeeData> = {
  dataMode: 'server',
  editMode: 'inline',
  columns: [
    {
      key: 'id',
      header: 'Employee ID',
      type: 'text',
      width: '120px',
      align: 'right',
      sortable: true,
      mobileVisible: true,
    },
    {
      key: 'fullName',
      header: 'Full Name',
      type: 'text',
      width: '180px',
      align: 'right',
      sortable: true,
      mobileVisible: true,
    },
    {
      key: 'email',
      header: 'Email',
      type: 'text',
      width: '220px',
      align: 'right',
      sortable: false,
      mobileVisible: false,
    },
    {
      key: 'phone',
      header: 'Phone',
      type: 'text',
      width: '140px',
      align: 'right',
      sortable: false,
      mobileVisible: false,
    },
    {
      key: 'department',
      header: 'Department',
      type: 'text',
      width: '140px',
      align: 'right',
      sortable: true,
      mobileVisible: false,
    },
    {
      key: 'position',
      header: 'Position',
      type: 'text',
      width: '160px',
      align: 'right',
      sortable: true,
      mobileVisible: false,
    },
    {
      key: 'salary',
      header: 'Salary',
      type: 'currency',
      width: '120px',
      align: 'right',
      sortable: true,
      mobileVisible: false,
      format: (value: number) => `₪ ${value.toLocaleString('he-IL')}`,
      styleConfig: {
        condition: (value) => typeof value === 'number' && value > 25000,
        backgroundColor: '#e8f5e9',
        textColor: '#2e7d32',
      },
    },
    {
      key: 'status',
      header: 'Status',
      type: 'badge',
      width: '120px',
      align: 'right',
      sortable: true,
      mobileVisible: true,
    },
    {
      key: 'startDate',
      header: 'Start Date',
      type: 'date',
      width: '120px',
      align: 'right',
      sortable: true,
      mobileVisible: false,
    },
    {
      key: 'birthDate',
      header: 'Birth Date',
      type: 'date',
      width: '120px',
      align: 'right',
      sortable: true,
      mobileVisible: false,
    },
    {
      key: 'actions',
      header: 'Actions',
      type: 'action',
      width: '100px',
      align: 'right',
      sortable: false,
      mobileVisible: true,
    },
  ],

  pagination: {
    defaultPageSize: 6,
    pageSizeOptions: [6, 10, 20, 50],
    showPageInfo: true,
  },

  virtualization: {
    enabled: false,
    itemSize: 52,
    mobileItemSize: 160,
    maxViewportHeight: 520,
  },

  features: {
    enableEdit: true,
    enableDelete: true,
    enableSearch: true,
    showTotalCount: false,
    enableFilters: true,
    enableSort: true,
    enableSelection: true,
  },

  styling: {
    statusColors: {
      active: '#4CAF50',
      remote: '#2196F3',
      onLeave: '#FFC107',
      inactive: '#9E9E9E',
    },
  },

  statusTypes: ['active', 'remote', 'onLeave', 'inactive'],
};
